edition = "2021"
style_edition = "2024"
max_width = 80
wrap_comments = true
comment_width = 80
hard_tabs = false
tab_spaces = 2
binop_separator = "Back"
error_on_line_overflow = true
error_on_unformatted = true
