DROP USER IF EXISTS '@USUARIO'@'localhost';

CREATE USER '@USUARIO'@'localhost' IDENTIFIED VIA unix_socket;

GRANT SELECT, INSERT, UPDATE, DELETE ON @DB_NOMBRE.* TO '@USUARIO'@'localhost';

FLUSH PRIVILEGES;